### ISSUE TITLE
meta-issue arbitrum deployment

### ISSUE THREAD

**Issue by omarryehia2** [Lagrange-Labs/lagrange-node#403]
## Tasks

- [ ] Register the aribitrum chain on the Holesky committee SC and deploy the sequencer and server
- [ ] Onboarding operators to subscribe Arbitrum chain on Holesky
- [ ] Write the script to register the arbitrum chain on the Mainnet and deployment
- [ ] Onboarding operators on mainnet for Arbitrum
